![Illustration of silhouetted heads](mentalhealth.jpg)

Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population, and that social connectedness (belonging to a social group) and acculturative stress (stress associated with joining a new culture) are predictive of depression.


Explore the `students` data using PostgreSQL to find out if you would come to a similar conclusion for international students and see if the length of stay is a contributing factor.

Here is a data description of the columns you may find helpful.

| Field Name    | Description                                      |
| ------------- | ------------------------------------------------ |
| `inter_dom`     | Types of students (international or domestic)   |
| `japanese_cate` | Japanese language proficiency                    |
| `english_cate`  | English language proficiency                     |
| `academic`      | Current academic level (undergraduate or graduate) |
| `age`           | Current age of student                           |
| `stay`          | Current length of stay in years                  |
| `todep`         | Total score of depression (PHQ-9 test)           |
| `tosc`          | Total score of social connectedness (SCS test)   |
| `toas`          | Total score of acculturative stress (ASISS test) |

In [2]:
-- UNDERSTANDING THE STUDENTS TABLE
SELECT * 
FROM students;

    inter_dom region  gender  ... alone_bi  others_bi  internet_bi
0       Inter    SEA    Male  ...       No         No           No
1       Inter    SEA    Male  ...       No         No           No
2       Inter    SEA    Male  ...       No         No           No
3       Inter     EA  Female  ...       No         No           No
4       Inter     EA  Female  ...       No         No           No
..        ...    ...     ...  ...      ...        ...          ...
281                           ...
282                           ...
283                           ...
284                           ...
285                           ...

[286 rows x 50 columns]

In [3]:
-- DATA EXPLORATION.

-- Exploring how the lenght of stay impacts the average mental health diagnostics scores of the international students
SELECT 
	stay, ROUND(COUNT(inter_dom), 2) AS count_int, ROUND(AVG(todep), 2) AS average_phq,
	ROUND(AVG(tosc), 2) AS average_scs, ROUND(AVG(toas), 2) AS average_as

FROM students
WHERE inter_dom = 'Inter'
GROUP  BY stay 
ORDER BY stay DESC;

   stay  count_int  average_phq  average_scs  average_as
0    10        1.0        13.00        32.00       50.00
1     8        1.0        10.00        44.00       65.00
2     7        1.0         4.00        48.00       45.00
3     6        3.0         6.00        38.00       58.67
4     5        1.0         0.00        34.00       91.00
5     4       14.0         8.57        33.93       87.71
6     3       46.0         9.09        37.13       78.00
7     2       39.0         8.28        37.08       77.67
8     1       95.0         7.48        38.11       72.80

# Beyond Length of Stay: Exploring Student Mental Health with SQL

## Project Overview

This project extends DataCamp's *Analyzing Students' Mental Health*
guided SQL project using survey data from an international university
in Japan.

The original analysis focused on whether the length of time
international students had lived in Japan was associated with
depression, social connectedness, and acculturative stress.

I extended the analysis to first assess the quality and structure of the
dataset, understand the survey population, compare international and
domestic students, and then revisit the length-of-stay question while
considering the reliability of group-level averages.

The objective is not simply to calculate summary statistics, but to
demonstrate how data quality, sample composition, and sample size affect
the interpretation of mental-health survey data.

**Tool:** PostgreSQL / SQL  
**Environment:** DataCamp DataLab

## Extended Analysis: Data Understanding and Quality Assessment

Before extending the analysis, I examined the dataset to understand its
structure, identify incomplete or unusual records, and determine which
observations should be included in the analysis.

This step is important because conclusions about student mental health
should be based only on valid student responses.

### Are all rows actual student records?

In [4]:
SELECT
    COUNT(*) AS total_rows,

    COUNT(*) FILTER (
        WHERE inter_dom IN ('Inter', 'Dom')
    ) AS valid_student_records,

    COUNT(*) FILTER (
        WHERE TRIM(COALESCE(inter_dom, '')) = ''
    ) AS non_student_rows

FROM students;

   total_rows  valid_student_records  non_student_rows
0         286                    268                18

### Data Quality Finding: Non-Student Rows

The raw dataset contains 286 rows, but only 268 represent individual
student responses.

The remaining 18 rows have blank values for `inter_dom` and contain
summary or aggregate values rather than complete respondent-level
records. These rows are therefore not valid student observations.

**Decision:** The original dataset will be preserved unchanged, while
all subsequent student-level analysis will be restricted to records
where `inter_dom` is either `Inter` or `Dom`.

### Missing Value Assessment

After identifying the valid student records, I checked whether important
demographic, mental-health, and help-seeking variables contained missing
values that could affect the analysis.

In [5]:
WITH valid_students AS (
    SELECT *
    FROM students
    WHERE inter_dom IN ('Inter', 'Dom')
),

column_values AS (
    SELECT
        j.key AS column_name,
        j.value AS column_value
    FROM valid_students s
    CROSS JOIN LATERAL jsonb_each_text(to_jsonb(s)) AS j(key, value)
)

SELECT
    column_name,
    COUNT(*) AS total_records,

    COUNT(*) FILTER (
        WHERE column_value IS NULL
           OR TRIM(column_value) = ''
    ) AS missing_values,

    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE column_value IS NULL
               OR TRIM(column_value) = ''
        )
        / COUNT(*),
        2
    ) AS missing_percentage

FROM column_values
GROUP BY column_name
ORDER BY missing_values DESC, column_name;

        column_name  total_records  missing_values  missing_percentage
0          internet            268              26                9.70
1          intimate            268               8                2.99
2          academic            268               0                0.00
3               acs            268               0                0.00
4             afear            268               0                0.00
5               age            268               0                0.00
6          age_cate            268               0                0.00
7            aguilt            268               0                0.00
8             ahome            268               0                0.00
9             alone            268               0                0.00
10         alone_bi            268               0                0.00
11         amiscell            268               0                0.00
12              apd            268               0                0.00
13              aph            268               0                0.00
14              dep            268               0                0.00
15           depsev            268               0                0.00
16          deptype            268               0                0.00
17           doctor            268               0                0.00
18        doctor_bi            268               0                0.00
19          english            268               0                0.00
20     english_cate            268               0                0.00
21          friends            268               0                0.00
22       friends_bi            268               0                0.00
23           gender            268               0                0.00
24        inter_dom            268               0                0.00
25      internet_bi            268               0                0.00
26         japanese            268               0                0.00
27    japanese_cate            268               0                0.00
28           others            268               0                0.00
29        others_bi            268               0                0.00
30          parents            268               0                0.00
31       parents_bi            268               0                0.00
32          partner            268               0                0.00
33       partner_bi            268               0                0.00
34            phone            268               0                0.00
35         phone_bi            268               0                0.00
36          profess            268               0                0.00
37  professional_bi            268               0                0.00
38           region            268               0                0.00
39         relative            268               0                0.00
40      relative_bi            268               0                0.00
41             reli            268               0                0.00
42         religion            268               0                0.00
43      religion_bi            268               0                0.00
44             stay            268               0                0.00
45        stay_cate            268               0                0.00
46          suicide            268               0                0.00
47             toas            268               0                0.00
48            todep            268               0                0.00
49             tosc            268               0                0.00

### Missing-Value Findings

A comprehensive assessment of all variables identified missing values in
only two columns among the 268 valid student records:

- `internet`: 26 missing values (9.70%)
- `intimate`: 8 missing values (2.99%)

All other variables, including the main mental-health measures
(`todep`, `tosc`, and `toas`), are complete.

No records were removed at this stage. The missing values will be
investigated further and handled only when analyses involving these
specific variables are performed.

In [6]:
SELECT
    inter_dom,
    academic,
    gender,
    age,
    intimate
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
  AND (
      intimate IS NULL
      OR TRIM(intimate) = ''
  );

  inter_dom academic  gender  age  intimate
0     Inter     Grad    Male   24       NaN
1     Inter     Grad    Male   28       NaN
2     Inter    Under  Female   19       NaN
3     Inter    Under    Male   25       NaN
4     Inter    Under    Male   18       NaN
5     Inter    Under    Male   18       NaN
6     Inter    Under    Male   19       NaN
7     Inter    Under    Male   20       NaN

In [7]:
SELECT
    inter_dom,
    dep,
    internet,
    internet_bi
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
  AND (
      internet IS NULL
      OR TRIM(CAST(internet AS TEXT)) = ''
  );

   inter_dom  dep  internet internet_bi
0      Inter   No       NaN          No
1      Inter   No       NaN          No
2      Inter   No       NaN          No
3      Inter   No       NaN          No
4      Inter   No       NaN          No
5      Inter   No       NaN          No
6      Inter   No       NaN          No
7      Inter   No       NaN          No
8      Inter  Yes       NaN          No
9      Inter   No       NaN          No
10     Inter   No       NaN          No
11     Inter   No       NaN          No
12     Inter   No       NaN          No
13     Inter   No       NaN          No
14     Inter   No       NaN          No
15     Inter  Yes       NaN          No
16     Inter   No       NaN          No
17     Inter   No       NaN          No
18     Inter   No       NaN          No
19     Inter   No       NaN          No
20     Inter   No       NaN          No
21     Inter   No       NaN          No
22     Inter  Yes       NaN          No
23     Inter   No       NaN          No
24     Inter  Yes       NaN          No
25       Dom  Yes       NaN          No

### Missing-Intimate Values

The 8 missing values in `intimate` occur only among international
students. Because there is no reliable information from which to infer
their relationship status, these values will not be imputed. The
students will remain in the dataset and will only be excluded from any
analysis that specifically requires `intimate`.

The 26 missing values in the numerical `internet` variable require
further investigation because the corresponding binary variable,
`internet_bi`, is still populated. I therefore examined the relationship
between the original numerical score and its binary representation
before deciding how the missing values should be handled.

In [8]:
SELECT
    internet,
    internet_bi,
    COUNT(*) AS student_count
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY internet, internet_bi
ORDER BY internet NULLS LAST, internet_bi;

   internet internet_bi  student_count
0       NaN          No             26
1       1.0          No             68
2       2.0          No             32
3       3.0          No             45
4       4.0          No             52
5       5.0         Yes             25
6       6.0         Yes              9
7       7.0         Yes             11

### Missing-Internet Values

The numerical `internet` variable contains 26 missing responses.

For students with a recorded numerical score, the corresponding binary
variable (`internet_bi`) follows a consistent rule:

- Scores 1–4 are classified as `No`
- Scores 5–7 are classified as `Yes`

However, all 26 records with a missing numerical `internet` value are
also classified as `No` in `internet_bi`.

Because the original numerical response is unavailable, these 26 cases
cannot confidently be interpreted as genuine `No` responses.

**Decision:** Analyses using the numerical `internet` variable will use
only students with a recorded score. If a binary Internet help-seeking
measure is required, it will be derived from the observed numerical
scores rather than treating missing responses as `No`.

### Duplicate Handling Decision

The dataset does not contain a unique respondent identifier, so duplicate
responses cannot be verified reliably.

For this analysis, the 268 valid student records are retained as provided
in the source dataset. No records are removed on the basis of assumed
duplication.

### Range and Category Validation

Before beginning the exploratory analysis, I checked the ranges of the
main numerical variables and the categories used in the analysis to
identify unexpected or invalid values.

In [9]:
SELECT
    MIN(age) AS min_age,
    MAX(age) AS max_age,

    MIN(stay) AS min_stay,
    MAX(stay) AS max_stay,

    MIN(japanese) AS min_japanese,
    MAX(japanese) AS max_japanese,

    MIN(english) AS min_english,
    MAX(english) AS max_english,

    MIN(todep) AS min_phq,
    MAX(todep) AS max_phq,

    MIN(tosc) AS min_scs,
    MAX(tosc) AS max_scs,

    MIN(toas) AS min_acculturative_stress,
    MAX(toas) AS max_acculturative_stress

FROM students
WHERE inter_dom IN ('Inter', 'Dom');

   min_age  max_age  ...  min_acculturative_stress  max_acculturative_stress
0       17       31  ...                        36                       145

[1 rows x 14 columns]

In [10]:
SELECT 'inter_dom' AS variable, inter_dom AS category, COUNT(*) AS student_count
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom

UNION ALL

SELECT 'gender', gender, COUNT(*)
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY gender

UNION ALL

SELECT 'academic', academic, COUNT(*)
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY academic

UNION ALL

SELECT 'stay_cate', stay_cate, COUNT(*)
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY stay_cate

UNION ALL

SELECT 'japanese_cate', japanese_cate, COUNT(*)
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY japanese_cate

UNION ALL

SELECT 'english_cate', english_cate, COUNT(*)
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY english_cate

UNION ALL

SELECT 'depsev', depsev, COUNT(*)
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY depsev

         variable category  student_count
0       inter_dom      Dom             67
1       inter_dom    Inter            201
2          gender   Female            170
3          gender     Male             98
4        academic     Grad             21
5        academic    Under            247
6       stay_cate     Long             32
7       stay_cate   Medium            121
8       stay_cate    Short            115
9   japanese_cate  Average             89
10  japanese_cate     High             87
11  japanese_cate      Low             92
12   english_cate  Average             80
13   english_cate     High            166
14   english_cate      Low             22
15         depsev     Mild            107
16         depsev      Min             65
17         depsev      Mod             73
18         depsev   ModSev             15
19         depsev      Sev              8

## 2. Student Population Profile

Before examining mental-health outcomes, I first explored the composition
of the survey sample. Understanding who is represented in the data
provides important context for interpreting later comparisons.

In [11]:
SELECT
    inter_dom,
    COUNT(*) AS student_count,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom
ORDER BY student_count DESC;

  inter_dom  student_count  percentage
0     Inter            201        75.0
1       Dom             67        25.0

### Finding

International students make up 75% of the survey sample, while domestic
students account for 25%. Because the two groups are unequal in size,
later comparisons should consider both the average outcome and the
number of students represented in each group.

In [12]:
SELECT
    inter_dom,
    gender,
    COUNT(*) AS student_count,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY inter_dom),
        2
    ) AS percentage_within_group
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom, gender
ORDER BY inter_dom, student_count DESC;

  inter_dom  gender  student_count  percentage_within_group
0       Dom  Female             42                    62.69
1       Dom    Male             25                    37.31
2     Inter  Female            128                    63.68
3     Inter    Male             73                    36.32

### Finding

The gender distribution is similar across both student groups.

- Domestic students: 62.69% female and 37.31% male
- International students: 63.68% female and 36.32% male

Because the gender proportions are nearly identical, differences observed
later between international and domestic students are less likely to be
explained simply by differences in gender composition.

### What is the academic-level composition of each student group?

In [13]:
SELECT
    inter_dom,
    academic,
    COUNT(*) AS student_count,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY inter_dom),
        2
    ) AS percentage_within_group
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom, academic
ORDER BY inter_dom, student_count DESC;

  inter_dom academic  student_count  percentage_within_group
0       Dom    Under             66                    98.51
1       Dom     Grad              1                     1.49
2     Inter    Under            181                    90.05
3     Inter     Grad             20                     9.95

### Finding

Both student groups are predominantly undergraduate. However, graduate
students make up 9.95% of the international sample compared with only
1.49% of the domestic sample.

This difference in academic composition should be kept in mind when
comparing mental-health outcomes between international and domestic
students, since the two groups are not identical in their academic-level
distribution.

### How does age differ between international and domestic students?

In [14]:
SELECT
    inter_dom,
    COUNT(*) AS student_count,
    ROUND(AVG(age), 0) AS average_age,
    MIN(age) AS minimum_age,
    MAX(age) AS maximum_age
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom
ORDER BY inter_dom;

  inter_dom  student_count  average_age  minimum_age  maximum_age
0       Dom             67           20           18           27
1     Inter            201           21           17           31

In [15]:
SELECT
    inter_dom,
    age_cate,
    COUNT(*) AS student_count,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY inter_dom),
        2
    ) AS percentage_within_group
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom, age_cate
ORDER BY inter_dom, age_cate;

  inter_dom  age_cate  student_count  percentage_within_group
0       Dom         1              9                    13.43
1       Dom         2             27                    40.30
2       Dom         3             25                    37.31
3       Dom         4              5                     7.46
4       Dom         5              1                     1.49
5     Inter         1             31                    15.42
6     Inter         2             75                    37.31
7     Inter         3             53                    26.37
8     Inter         4             27                    13.43
9     Inter         5             15                     7.46

### Finding

The average ages of international and domestic students are relatively
similar at 21.03 and 20.40 years respectively.

However, international students have a broader age range (17–31 years)
than domestic students (18–27 years) and are more represented in the
higher age categories.

Together with the academic-level results, this suggests that the
international sample includes a somewhat larger share of older and
graduate students. These compositional differences will be considered
when interpreting later comparisons between the two groups.

### Population Profile Summary

The survey sample consists primarily of international, female, and
undergraduate students. International and domestic students have very
similar gender distributions and broadly similar average ages.

The main compositional differences are the larger sample size of
international students and their greater representation among graduate
and older students. These differences provide context for the
mental-health comparisons that follow.

## 3. Mental Health Profile

After understanding the composition of the survey population, the next
step is to examine the mental-health measures captured in the dataset.

The analysis focuses primarily on three measures:

- **PHQ (`todep`)** – depression score
- **SCS (`tosc`)** – social connectedness score
- **ASISS (`toas`)** – acculturative stress score

Higher PHQ scores indicate greater depressive symptoms, higher SCS
scores indicate stronger social connectedness, and higher ASISS scores
indicate greater acculturative stress.

In [16]:
SELECT
    COUNT(*) AS student_count,
    ROUND(AVG(todep), 2) AS average_phq,
    ROUND(AVG(tosc), 2) AS average_scs,
    ROUND(AVG(toas), 2) AS average_acculturative_stress
FROM students
WHERE inter_dom IN ('Inter', 'Dom');

   student_count  average_phq  average_scs  average_acculturative_stress
0            268         8.19        37.47                         72.38

In [17]:
SELECT
    depsev AS depression_severity,
    COUNT(*) AS student_count,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY depsev
ORDER BY
    CASE depsev
        WHEN 'Min' THEN 1
        WHEN 'Mild' THEN 2
        WHEN 'Mod' THEN 3
        WHEN 'ModSev' THEN 4
        WHEN 'Sev' THEN 5
    END;

  depression_severity  student_count  percentage
0                 Min             65       24.25
1                Mild            107       39.93
2                 Mod             73       27.24
3              ModSev             15        5.60
4                 Sev              8        2.99

## 4. International vs Domestic Students

After examining the overall mental-health profile of the survey sample,
I compared international and domestic students to determine whether the
two groups show differences in depression, social connectedness, and
acculturative stress.

### How do the average mental-health scores differ between international and domestic students?

In [18]:
SELECT
    inter_dom,
    COUNT(*) AS student_count,
    ROUND(AVG(todep), 2) AS average_phq,
    ROUND(AVG(tosc), 2) AS average_scs,
    ROUND(AVG(toas), 2) AS average_acculturative_stress
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom
ORDER BY inter_dom;

  inter_dom  student_count  ...  average_scs  average_acculturative_stress
0       Dom             67  ...        37.64                         62.84
1     Inter            201  ...        37.42                         75.56

[2 rows x 5 columns]

In [19]:
SELECT
    inter_dom,
    depsev AS depression_severity,
    COUNT(*) AS student_count,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY inter_dom),
        2
    ) AS percentage_within_group
FROM students
WHERE inter_dom IN ('Inter', 'Dom')
GROUP BY inter_dom, depsev
ORDER BY
    inter_dom,
    CASE depsev
        WHEN 'Min' THEN 1
        WHEN 'Mild' THEN 2
        WHEN 'Mod' THEN 3
        WHEN 'ModSev' THEN 4
        WHEN 'Sev' THEN 5
    END;

  inter_dom depression_severity  student_count  percentage_within_group
0       Dom                 Min             14                    20.90
1       Dom                Mild             26                    38.81
2       Dom                 Mod             20                    29.85
3       Dom              ModSev              4                     5.97
4       Dom                 Sev              3                     4.48
5     Inter                 Min             51                    25.37
6     Inter                Mild             81                    40.30
7     Inter                 Mod             53                    26.37
8     Inter              ModSev             11                     5.47
9     Inter                 Sev              5                     2.49

### Finding

The depression-severity distribution does not show international students
consistently experiencing more severe depressive symptoms than domestic
students.

Domestic students have a somewhat larger proportion of respondents in
the moderate, moderately severe, and severe categories, while
international students have a larger proportion in the minimal and mild
categories.

This suggests that differences between international and domestic
students may be more complex than depression severity alone and should
be examined alongside social connectedness and acculturative stress.

## 5. Length of Stay and Mental Health Among International Students

The original DataCamp analysis examined whether the length of time
international students had lived in Japan was associated with their
mental-health scores.

In this extended analysis, I revisit that question while also considering
the number of students represented at each length of stay. This is
important because averages based on very small groups may not be
representative.

In [20]:
SELECT
    stay,
    COUNT(*) AS student_count,
    ROUND(AVG(todep), 2) AS average_phq,
    ROUND(AVG(tosc), 2) AS average_scs,
    ROUND(AVG(toas), 2) AS average_acculturative_stress
FROM students
WHERE inter_dom = 'Inter'
GROUP BY stay
ORDER BY stay;

   stay  student_count  average_phq  average_scs  average_acculturative_stress
0     1             95         7.48        38.11                         72.80
1     2             39         8.28        37.08                         77.67
2     3             46         9.09        37.13                         78.00
3     4             14         8.57        33.93                         87.71
4     5              1         0.00        34.00                         91.00
5     6              3         6.00        38.00                         58.67
6     7              1         4.00        48.00                         45.00
7     8              1        10.00        44.00                         65.00
8    10              1        13.00        32.00                         50.00

### Finding

Among the better-represented stay groups (1–4 years), acculturative stress
generally increases with length of stay, while social connectedness tends
to decline. Depression scores also rise between years 1 and 3, although
the pattern is not strictly linear.

However, the number of students drops sharply after four years. Several
later stay groups contain only one respondent, making their averages too
unstable for reliable comparison.

For this reason, exact-year averages are interpreted cautiously and a
broader stay-category analysis is used to obtain a more stable view of
the relationship.

In [21]:
SELECT
    stay_cate,
    COUNT(*) AS student_count,
    ROUND(AVG(todep), 2) AS average_phq,
    ROUND(AVG(tosc), 2) AS average_scs,
    ROUND(AVG(toas), 2) AS average_acculturative_stress
FROM students
WHERE inter_dom = 'Inter'
GROUP BY stay_cate
ORDER BY
    CASE stay_cate
        WHEN 'Short' THEN 1
        WHEN 'Medium' THEN 2
        WHEN 'Long' THEN 3
    END;

  stay_cate  student_count  ...  average_scs  average_acculturative_stress
0     Short             95  ...        38.11                         72.80
1    Medium             85  ...        37.11                         77.85
2      Long             21  ...        35.57                         78.81

[3 rows x 5 columns]

### Finding

When length of stay is grouped into broader categories, a clearer pattern
emerges.

Average acculturative stress increases from 72.80 among short-stay
students to 78.81 among long-stay students, while average social
connectedness declines from 38.11 to 35.57.

Depression scores do not follow the same linear pattern. PHQ increases
from 7.48 in the short-stay group to 8.72 in the medium-stay group before
declining to 7.86 among long-stay students.

Overall, the results suggest that longer residence is more consistently
associated with higher acculturative stress and lower social
connectedness than with steadily increasing depressive symptoms.

## 6. Key Findings

The extended analysis produced four main findings:

1. **The survey sample is dominated by international students.**  
   Of the 268 valid student records, 75% are international students and
   25% are domestic students. Gender composition is very similar between
   the two groups, although international students include a larger
   proportion of graduate and older students.

2. **Depression severity does not show a simple international-versus-domestic pattern.**  
   Domestic students have a somewhat larger proportion of respondents in
   the moderate, moderately severe, and severe depression categories.
   This suggests that international-student mental health cannot be
   understood through depression severity alone.

3. **Exact-year comparisons of length of stay can be misleading.**  
   International students who had stayed for more than four years were
   represented by very small samples, with several year groups containing
   only one respondent. These averages were therefore treated cautiously.

4. **Broader stay categories reveal a clearer pattern.**  
   Among international students, average acculturative stress increased
   from 72.80 for short-stay students to 78.81 for long-stay students,
   while social connectedness declined from 38.11 to 35.57.

   Depression scores did not increase consistently with length of stay,
   suggesting that longer residence is more clearly associated with
   acculturative stress and social connectedness than with steadily
   increasing depressive symptoms.

## 7. Limitations and Conclusion

### Limitations

This analysis is based on survey data from one university and therefore
should not be generalized to all international or domestic students.

The dataset is cross-sectional, so the observed relationships cannot be
interpreted as causal effects.

Some length-of-stay groups contained very few students, which made
exact-year averages unstable. Broader stay categories were therefore used
to support more reliable comparisons.

The dataset also contained 18 non-student summary rows, which were
excluded from respondent-level analysis. Missing values were found in
the `internet` and `intimate` variables and were handled only when those
variables were relevant to an analysis.

### Conclusion

The analysis suggests that the mental-health experience of international
students is more complex than a simple relationship between time spent
abroad and depression.

While depressive symptoms did not increase consistently with length of
stay, longer-stay international students showed higher average
acculturative stress and lower social connectedness.

This highlights an important analytical distinction: remaining in a host
country for longer does not necessarily imply easier adjustment.

More broadly, the project demonstrates why sample size, data quality and
the structure of grouped data should be considered before interpreting
averages or drawing conclusions from survey data.